train: /home/marek/Desktop/Dataset for Rust Detection/train/images
val: /home/marek/Desktop/Dataset for Rust Detection/valid/images
test: /home/marek/Desktop/Dataset for Rust Detection/test/images

nc: 10
names: ['Rust', 'car', 'copper corrosion', 'corroded-part', 'corrosion', 'iron rust', 'mild-corrosion', 'moderate-corrosion', 'rust', 'severe-corrosion']

roboflow:
  workspace: rust-detection
  project: rust-detection-38s6e
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/rust-detection/rust-detection-38s6e/dataset/1